stock_config:
  start_date: "2015-01-01"
  end_date: "2025-01-01"
  company_list:
    - "GOOGL"
    - "AAPL"
    - "MSFT"
    - "AMZN"
    - "META"
    - "NVDA"
  dataset_path: "data/processed"
  scaled_data_file_name: "scaled_data.csv"

model:
  attention_heads: 1
  gru_l1_hidden_size: 64
  gru_l1_layers: 1
  gru_l2_hidden_size: 64
  gru_l2_layers: 1
  gru_decoder_hidden_size: 64
  gru_decoder_layers: 1


training:
  BATCH_SIZE: 128
  EPOCHS: 1000
  WEIGHT_DECAY: 1e-8
  LEARNING_RATE: 1e-5
  N_PRED: 10
  N_HIST: 50
  DROPOUT: 0.01
  training_percent: 0.88
  validation_percent: 0.1
  test_percent: 0.02
  shuffle_data: true
  checkpoint_dir: "runs"
  do_training: true  # MUST BE False WHEN DOING ONLY INFERENCE STEP AFTER TRAINING

inference:
  output_dir: "inference_results"
  node: "GOOGL"
  step: 1 # between 0 and N_PRED-1 from training!!
